version: "3.8"
services:
  api:
    container_name: learn-nestjs
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /learn-nestjs