version: '3.7'
services:
  api-server:
    container_name: api-server
    build: .
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /api-server
    depends_on:
      - db-server
      
  db-server:
    container_name: db-server
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd

