version: '3.8'
services:
  api-server:
    container_name: api-server
    build: .
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /api-server
    depends_on:
      - learn-nestjs-db-server
      
  learn-nestjs-db-server:
    container_name: learn-nestjs-db-server
    volumes:
      - data-volume:/var/lib/mysql
    image: mariadb:10.10.2
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: learn_nestjs
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  data-volume:
